"""
FinVox — API Schemas
Defines request and response validation models using Pydantic for the FastAPI integration.
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any


# ── Auth Endpoints Schemas ────────────────────────────────────────────────────

class UserRegisterRequest(BaseModel):
    """Schema for user registration."""
    username: str = Field(..., description="Desired username", example="johndoe")
    email: str = Field(..., description="User's email address", example="john@example.com")
    password: str = Field(..., description="User's password", min_length=6)

class UserLoginRequest(BaseModel):
    """Schema for user login."""
    username: str = Field(..., description="Username or email", example="johndoe")
    password: str = Field(..., description="User's password")

class AuthResponse(BaseModel):
    """Schema for authentication response (JWT placeholder)."""
    access_token: str = Field(..., description="JWT Access Token (or placeholder for now)")
    token_type: str = Field("bearer", description="Token type")
    user_id: str = Field(..., description="The ID of the authenticated user")


# ── Chat Endpoint Schemas ─────────────────────────────────────────────────────

class ChatRequest(BaseModel):
    """Schema for incoming chat messages from the frontend."""
    user_id: str = Field(
        ..., 
        description="Unique identifier for the user (e.g., 'usr_123' or email)",
        example="test_user_finvox"
    )
    session_id: str = Field(
        ..., 
        description="Unique identifier for the current chat session to maintain memory/context",
        example="session_comprehensive_01"
    )
    message: str = Field(
        ..., 
        description="The actual text message or query from the user",
        example="What is my total cash flow for July 2026?"
    )
    metadata: Optional[Dict[str, Any]] = Field(
        default_factory=dict, 
        description="Optional additional context (e.g., specific company context, UI state)"
    )


class ChatResponse(BaseModel):
    """Schema for the orchestrator's response sent back to the frontend."""
    session_id: str = Field(
        ..., 
        description="The session ID associated with this response"
    )
    answer: str = Field(
        ..., 
        description="The final natural language response generated by the agent"
    )
    routes: List[str] = Field(
        default_factory=list, 
        description="The sub-agent routes taken (e.g., ['cashflow_agent'], ['rag_agent', 'market_agent'])"
    )
    tool_output: Optional[str] = Field(
        None, 
        description="Raw output from executed tools/queries (useful for debugging or UI expansion panels)"
    )
    latency_ms: int = Field(
        0,
        description="Total processing time in milliseconds"
    )

# ── Chat Session Metadata Schemas ─────────────────────────────────────────────

class ChatSessionMeta(BaseModel):
    id: str = Field(..., description="Session UUID")
    user_id: str = Field(..., description="User's username")
    title: str = Field(..., description="Chat session title")
    created_at: str = Field(..., description="Creation timestamp")
    updated_at: str = Field(..., description="Last update timestamp")

class ChatSessionListResponse(BaseModel):
    sessions: List[ChatSessionMeta]

class ChatSessionCreateRequest(BaseModel):
    user_id: str = Field(..., description="User's username")
    title: Optional[str] = Field(None, description="Optional title, auto-generated if omitted")

class ChatSessionUpdateRequest(BaseModel):
    title: str = Field(..., description="New title for the session")


# ── Data Ingestion Schemas ────────────────────────────────────────────────────
# Note: For file uploads, FastAPI uses UploadFile. This is just for the metadata and response.

class IngestionMetadata(BaseModel):
    """Schema for metadata provided alongside file uploads."""
    user_id: str = Field(..., description="User uploading the file")
    description: Optional[str] = Field(None, description="Description of the file contents")
    company: Optional[str] = Field(None, description="Associated company name")
    year: Optional[str] = Field(None, description="Relevant financial year")
    # Add any other fields your DB or Qdrant might need as filterable metadata


class IngestionResponse(BaseModel):
    """Schema for the response after a file is ingested."""
    success: bool = Field(..., description="Whether ingestion was successful")
    document_id: str = Field(..., description="Unique ID assigned to this document/dataset")
    message: str = Field(..., description="Status message")
    
    # Specific to Vector DB (PDFs)
    chunks_processed: Optional[int] = Field(0, description="Number of text/table chunks created")
    upserted_count: Optional[int] = Field(0, description="Number of chunks successfully embedded and stored")
    
    # Specific to Relational DB (CSVs/Excel)
    supabase_table: Optional[str] = Field(None, description="Name of the dynamically created table")
    rows_inserted: Optional[int] = Field(0, description="Number of rows inserted into the table")
    
    error: Optional[str] = Field(None, description="Error details if success is False")


# ── System Health / Status ────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    """Basic health check schema."""
    status: str = Field("ok", description="Service status")
    version: str = Field("1.0.0", description="API Version")
    services: Dict[str, str] = Field(
        default_factory=dict, 
        description="Status of connected services (Supabase, Qdrant, LLM)"
    )
